# Exploratory Data Analysis (EDA)

Paths to data

In [2]:
PATH_EIVP_DATASET_MESURES = "../data/EIVP_DATASET_MESURES.xlsx"
# PATH_DFTRIE = "../data/dftrie.xlsx"
PATH_METEO = "../data/donnees-synop-essentielles-omm.xlsx"

dependencies

In [3]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.0.10-py2.py3-none-any.whl (242 kB)
     -------------------------------------- 242.1/242.1 KB 1.1 MB/s eta 0:00:00
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.10
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
You should consider upgrading via the 'c:\Users\Mustapha\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [4]:
import seaborn as sns
import pandas as pd

data= pd.read_excel(PATH_EIVP_DATASET_MESURES)
#data.describe()
data

,Unnamed: 0,TITLE,device_internal_id,humidity,noise,lum,battery,temp,voc,co2,hpa,sent_at
0,11802,EIVP,5BB4D0,20.5,33.0,84,127,23.8,3,450,1022,2021-04-13 17:04:00
1,11799,EIVP,5BB4D0,21.0,27.0,26,127,23.8,2,457,1022,2021-04-13 17:19:00
2,11796,EIVP,5BB4D0,21.5,27.0,18,127,23.8,2,452,1022,2021-04-13 17:34:00
3,11793,EIVP,5BB4D0,21.5,27.0,10,127,23.5,2,450,1022,2021-04-13 17:49:00
4,11790,EIVP,5BB4D0,22.0,34.5,8,127,23.5,2,455,1022,2021-04-13 18:04:00
...,...,...,...,...,...,...,...,...,...,...,...,...
2874,4,EIVP,5BB4D0,36.5,33.0,844,3234,22.5,3,412,997,2021-05-13 16:48:00
2875,3,EIVP,5BB4D0,37.0,33.0,1152,3225,22.8,3,401,997,2021-05-13 17:03:00
2876,2,EIVP,5BB4D0,36.5,30.0,750,3225,23.0,3,398,997,2021-05-13 17:18:00
2877,1,EIVP,5BB4D0,36.0,27.0,504,3225,23.0,3,407,997,2021-05-13 17:33:00
2878,0,EIVP,5BB4D0,36.0,27.0,602,3217,23.0,3,407,997,2021-05-13 17:48:00

In [5]:
data['sent_at'] = pd.to_datetime(data['sent_at'])
data = data.set_index('sent_at')
data.index

DatetimeIndex(['2021-04-13 17:04:00', '2021-04-13 17:19:00',
               '2021-04-13 17:34:00', '2021-04-13 17:49:00',
               '2021-04-13 18:04:00', '2021-04-13 18:19:00',
               '2021-04-13 18:34:00', '2021-04-13 18:49:00',
               '2021-04-13 19:04:00', '2021-04-13 19:19:00',
               ...
               '2021-05-13 15:33:00', '2021-05-13 15:48:00',
               '2021-05-13 16:03:00', '2021-05-13 16:18:00',
               '2021-05-13 16:33:00', '2021-05-13 16:48:00',
               '2021-05-13 17:03:00', '2021-05-13 17:18:00',
               '2021-05-13 17:33:00', '2021-05-13 17:48:00'],
              dtype='datetime64[ns]', name='sent_at', length=2879, freq=None)

In [6]:
from datetime import datetime
data[data.index < datetime.strptime('2021-04-13 20:00:00', "%Y-%m-%d %H:%M:%S")]

,Unnamed: 0,TITLE,device_internal_id,humidity,noise,lum,battery,temp,voc,co2,hpa
sent_at,,,,,,,,,,,
2021-04-13 17:04:00,11802,EIVP,5BB4D0,20.5,33.0,84,127,23.8,3,450,1022
2021-04-13 17:19:00,11799,EIVP,5BB4D0,21.0,27.0,26,127,23.8,2,457,1022
2021-04-13 17:34:00,11796,EIVP,5BB4D0,21.5,27.0,18,127,23.8,2,452,1022
2021-04-13 17:49:00,11793,EIVP,5BB4D0,21.5,27.0,10,127,23.5,2,450,1022
2021-04-13 18:04:00,11790,EIVP,5BB4D0,22.0,34.5,8,127,23.5,2,455,1022
2021-04-13 18:19:00,11787,EIVP,5BB4D0,22.5,27.0,4,127,23.3,2,453,1022
2021-04-13 18:34:00,11784,EIVP,5BB4D0,23.0,27.0,2,127,23.0,2,448,1022
2021-04-13 18:49:00,11781,EIVP,5BB4D0,23.5,27.0,0,127,22.8,2,442,1022
2021-04-13 19:04:00,11778,EIVP,5BB4D0,23.5,39.0,0,127,22.5,2,445,1022
2021-04-13 19:19:00,11775,EIVP,5BB4D0,24.0,27.0,0,127,22.5,2,440,1022
2021-04-13 19:34:00,11772,EIVP,5BB4D0,24.0,27.0,0,127,22.3,2,438,1022
2021-04-13 19:49:00,11769,EIVP,5BB4D0,24.5,27.0,0,127,22.0,2,428,1022

In [7]:
# data = data.reset_index()
# data = data.set_index('sent_at')
df = data.resample('3H', origin=datetime.strptime('2021-04-13 17:00:00', "%Y-%m-%d %H:%M:%S")).mean()
# data = data.reset_index()

In [8]:
df

,Unnamed: 0,humidity,noise,lum,battery,temp,voc,co2,hpa
sent_at,,,,,,,,,
2021-04-13 17:00:00,11785.5,22.625000,29.125000,12.666667,127.000000,23.066667,2.083333,446.500000,1022.000000
2021-04-13 20:00:00,11749.5,25.875000,28.041667,0.000000,127.000000,21.216667,2.000000,421.666667,1022.583333
2021-04-13 23:00:00,11713.5,27.125000,29.041667,0.000000,3760.666667,20.441667,2.000000,405.750000,1021.916667
2021-04-14 02:00:00,11677.5,27.583333,29.958333,0.000000,4087.000000,20.075000,2.000000,401.750000,1021.000000
2021-04-14 05:00:00,11641.5,26.750000,35.958333,10.666667,4083.000000,20.000000,2.000000,437.416667,1021.833333
...,...,...,...,...,...,...,...,...,...
2021-05-13 05:00:00,45.5,40.875000,41.000000,242.500000,3335.583333,20.000000,3.000000,412.916667,999.166667
2021-05-13 08:00:00,33.5,39.541667,40.958333,648.833333,3311.666667,20.425000,3.000000,407.666667,999.083333
2021-05-13 11:00:00,21.5,37.000000,37.416667,1268.666667,3280.083333,21.741667,3.000000,414.250000,998.250000
2021-05-13 14:00:00,9.5,35.166667,33.125000,483.666667,3249.916667,22.741667,3.000000,414.166667,997.166667
2021-05-13 17:00:00,1.5,36.375000,29.250000,752.000000,3223.000000,22.950000,3.000000,403.250000,997.000000

In [9]:
meteo = pd.read_excel(PATH_METEO)
meteo.head()

,ID OMM station,Date,Unnamed: 2,Pression au niveau mer,Variation de pression en 3 heures,Type de tendance baromÃƒÂ©trique,Direction du vent moyen 10 mn,Vitesse du vent moyen 10 mn,TempÃƒÂ©rature,Point de rosÃƒÂ©e,...,Altitude,communes (name),communes (code),EPCI (name),EPCI (code),department (name),department (code),region (name),region (code),mois_de_l_annee
0,7149.0,2021-04-13T17:00:00+02:00,NaN,103150.0,-120.0,7.0,40.0,4.0,283.55,270.85,...,89.0,Athis-Mons,91027.0,MÃƒÂ©tropole du Grand Paris,200054781.0,Essonne,91.0,ÃƒÅ½le-de-France,11.0,4.0
1,7149.0,2021-04-13T20:00:00+02:00,NaN,103100.0,-50.0,6.0,60.0,5.3,282.45,269.55,...,89.0,Athis-Mons,91027.0,MÃƒÂ©tropole du Grand Paris,200054781.0,Essonne,91.0,ÃƒÅ½le-de-France,11.0,4.0
2,7149.0,2021-04-13T23:00:00+02:00,NaN,103210.0,90.0,1.0,40.0,4.1,279.55,269.35,...,89.0,Athis-Mons,91027.0,MÃƒÂ©tropole du Grand Paris,200054781.0,Essonne,91.0,ÃƒÅ½le-de-France,11.0,4.0
3,7149.0,2021-04-14T02:00:00+02:00,NaN,103160.0,-60.0,8.0,40.0,3.1,276.85,270.05,...,89.0,Athis-Mons,91027.0,MÃƒÂ©tropole du Grand Paris,200054781.0,Essonne,91.0,ÃƒÅ½le-de-France,11.0,4.0
4,7149.0,2021-04-14T05:00:00+02:00,NaN,103080.0,-80.0,6.0,10.0,1.7,275.75,270.05,...,89.0,Athis-Mons,91027.0,MÃƒÂ©tropole du Grand Paris,200054781.0,Essonne,91.0,ÃƒÅ½le-de-France,11.0,4.0

In [10]:
meteo["Date"] = pd.to_datetime(meteo["Date"])
meteo['sent_at'] = pd.to_datetime(meteo['Date'].dt.tz_localize(None))

In [11]:
meteo.head()

,ID OMM station,Date,Unnamed: 2,Pression au niveau mer,Variation de pression en 3 heures,Type de tendance baromÃƒÂ©trique,Direction du vent moyen 10 mn,Vitesse du vent moyen 10 mn,TempÃƒÂ©rature,Point de rosÃƒÂ©e,...,communes (name),communes (code),EPCI (name),EPCI (code),department (name),department (code),region (name),region (code),mois_de_l_annee,sent_at
0,7149.0,2021-04-13 17:00:00+02:00,NaN,103150.0,-120.0,7.0,40.0,4.0,283.55,270.85,...,Athis-Mons,91027.0,MÃƒÂ©tropole du Grand Paris,200054781.0,Essonne,91.0,ÃƒÅ½le-de-France,11.0,4.0,2021-04-13 17:00:00
1,7149.0,2021-04-13 20:00:00+02:00,NaN,103100.0,-50.0,6.0,60.0,5.3,282.45,269.55,...,Athis-Mons,91027.0,MÃƒÂ©tropole du Grand Paris,200054781.0,Essonne,91.0,ÃƒÅ½le-de-France,11.0,4.0,2021-04-13 20:00:00
2,7149.0,2021-04-13 23:00:00+02:00,NaN,103210.0,90.0,1.0,40.0,4.1,279.55,269.35,...,Athis-Mons,91027.0,MÃƒÂ©tropole du Grand Paris,200054781.0,Essonne,91.0,ÃƒÅ½le-de-France,11.0,4.0,2021-04-13 23:00:00
3,7149.0,2021-04-14 02:00:00+02:00,NaN,103160.0,-60.0,8.0,40.0,3.1,276.85,270.05,...,Athis-Mons,91027.0,MÃƒÂ©tropole du Grand Paris,200054781.0,Essonne,91.0,ÃƒÅ½le-de-France,11.0,4.0,2021-04-14 02:00:00
4,7149.0,2021-04-14 05:00:00+02:00,NaN,103080.0,-80.0,6.0,10.0,1.7,275.75,270.05,...,Athis-Mons,91027.0,MÃƒÂ©tropole du Grand Paris,200054781.0,Essonne,91.0,ÃƒÅ½le-de-France,11.0,4.0,2021-04-14 05:00:00

In [12]:
df_merge = df.merge(meteo, on='sent_at')
df_merge.head()

,sent_at,Unnamed: 0,humidity,noise,lum,battery,temp,voc,co2,hpa,...,Altitude,communes (name),communes (code),EPCI (name),EPCI (code),department (name),department (code),region (name),region (code),mois_de_l_annee
0,2021-04-13 17:00:00,11785.5,22.625000,29.125000,12.666667,127.000000,23.066667,2.083333,446.500000,1022.000000,...,89.0,Athis-Mons,91027.0,MÃƒÂ©tropole du Grand Paris,200054781.0,Essonne,91.0,ÃƒÅ½le-de-France,11.0,4.0
1,2021-04-13 20:00:00,11749.5,25.875000,28.041667,0.000000,127.000000,21.216667,2.000000,421.666667,1022.583333,...,89.0,Athis-Mons,91027.0,MÃƒÂ©tropole du Grand Paris,200054781.0,Essonne,91.0,ÃƒÅ½le-de-France,11.0,4.0
2,2021-04-13 23:00:00,11713.5,27.125000,29.041667,0.000000,3760.666667,20.441667,2.000000,405.750000,1021.916667,...,89.0,Athis-Mons,91027.0,MÃƒÂ©tropole du Grand Paris,200054781.0,Essonne,91.0,ÃƒÅ½le-de-France,11.0,4.0
3,2021-04-14 02:00:00,11677.5,27.583333,29.958333,0.000000,4087.000000,20.075000,2.000000,401.750000,1021.000000,...,89.0,Athis-Mons,91027.0,MÃƒÂ©tropole du Grand Paris,200054781.0,Essonne,91.0,ÃƒÅ½le-de-France,11.0,4.0
4,2021-04-14 05:00:00,11641.5,26.750000,35.958333,10.666667,4083.000000,20.000000,2.000000,437.416667,1021.833333,...,89.0,Athis-Mons,91027.0,MÃƒÂ©tropole du Grand Paris,200054781.0,Essonne,91.0,ÃƒÅ½le-de-France,11.0,4.0

# Profile data

Using pandas profiler

In [13]:
# %pip install pandas-profiling[notebook]
# %pip install pandas-profiling

In [ ]:
from pandas_profiling import ProfileReport

# Generate the profile report
df_report = ProfileReport(df_merge.reset_index(drop=True))
df_report.to_file(output_file='../reports/merged_report.html')
df_report.to_notebook_iframe()